"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
import sys
sys.setrecursionlimit(5000)

APP = ['Assessment.py']
DATA_FILES = []
OPTIONS = {'iconfile': '/Users/jeremie/PycharmProjects/Python/Assessment/icon.icns',
           'packages': ['pandas', 'essential_generators']}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
